### ISSUE TITLE
Fix on mobile

### ISSUE THREAD

**Issue by janko-m** [twin/waldorfcamp-web#27]
* Footer je skocio na sredinu:

![image](https://cloud.githubusercontent.com/assets/795488/8227949/60d0a28e-15ab-11e5-9a99-ba8ca443ee63.jpg)

* Social ikonice nisu centrirane:

![image](https://cloud.githubusercontent.com/assets/795488/8227989/a90983ea-15ab-11e5-93bc-5b0acaa75bbc.jpg)

* Loader u galeriji se uvijek prikazuje na vrhu stranice, a trebao bi na dnu.

**Comment by janko-m** [comment]
Jebate, ne znam kako da s iPhonea smanjim te slike :stuck_out_tongue: .

**Comment by janko-m** [comment]
E, i jos pricing calculator nije responsive, nego moras horizontalno scrollati, a stvarno ima mjesta, tako da mislim da je samo slucajna greska.

**Comment by janko-m** [comment]
Izgleda da ovaj footer poskoči na gornji dio stranice općenito u Safariju, znači i na desktopu. Sori, nadam se da te nisam overwhelmao s bug reportovima :)

**Comment by silvenon** [comment]
Social ikonice namjerno nisu centrirane. Meni tako bolje izgleda.
