### ISSUE TITLE
Hardcodiranje slika

### ISSUE THREAD

**Issue by janko** [twin/waldorfcamp-web#28]
Ja bih svugdje osim na galeriji hardcodirao URL-ove slika, da uopce ne moras napraviti request na API. Na home pageu i workshops pageu bih ja dakle uzeo konkretne URL-ove. Sta mislis?

Jel radis mozda request na API cim netko dode na stranicu? Ja bih fakat to trebao deployati na DigitalOcean, ovaj Heroku je katastrofa, jednostavno mi se nije uspjelo loadirati sada. Probat cu to sto prije, ali u meduvremenu mislim da imas /heartbeat na kojeg mozes poslati request. Ili ne moras, mozes me cekati da deployam.

**Comment by silvenon** [comment]
Imaš pravo, trebao bih. Smijem li hotloadati s Flickra tako ili oni to ne žele?

**Comment by janko-m** [comment]
Pa mislim da mozes, jer tako ionako to sad tako radis, jedina je razlika da dobavljas tu informaciju dinamicki umjesto staticki.

Ja mislim da je jedini uvjet Flickra da ti slike moraju biti link na tu istu sliku na Flickru.

**Comment by silvenon** [comment]
S obzirom da je sad web statičan, slike se povlače s Cloudinaryja, ovo više nije relevantno.
