### ISSUE TITLE
Zemljopisna slika Oliba

### ISSUE THREAD

**Issue by janko-m** [twin/waldorfcamp-web#29]
Kad sam rekao da fali slika Oliba, zapravo sam mislio na kartografsku sliku, koju vidis na karti, onakvu kakvu smo imali na prosloj stranici. Sta mislis o tome?

**Comment by silvenon** [comment]
Misliš Google Maps `<iframe>`?

**Comment by janko-m** [comment]
Pa cak i je treba to, moze biti i staticna slika, ali sad kad se sjetim bila je Google maps slika prije, i to je bilo ok. Sta ti mislis? Mislim da je super da ljudi odmah mogu vidjeti gdje je Olib.

**Comment by silvenon** [comment]
Može, `<iframe>` onda.

**Comment by silvenon** [comment]
Malo mi se teško uklapa u dizajn, sviđa mi se ovo što imamo trenutno. A i mrzim `<iframe>`ove jer kad scrollaš i miš ti slučajno dođe na njega, prestane se scrollati i počne se zumirati (funkcionalnost Google Mapsa), što je dosta loš UX jer često to ne želiš nego si htio scrollati dalje.
