### ISSUE TITLE
Nejasnost u pricing kalkulatoru

### ISSUE THREAD

**Issue by janko-m** [twin/waldorfcamp-web#30]
Super si ga poboljsao, ali Dori i ja smo primjetili jednu nejasnost kada smo htjeli za nas racunati cijenu. Broj osoba i broj kreveta, nije jasna razlika izmedu tog dvoje. Sto ako kazes da dovodis jos jednu osobu, a broj kreveta ostavis na jedan? Da li taj broj kreveta mozda ne bi trebao postojati?

**Comment by silvenon** [comment]
E, to sam namjerno tako napravio. Npr. ti i Dori spavate u jednom krevetu, a vas je dvoje. Dakle činjenica da vas je dvoje je bitna zbog participation feea, hrane itd., ali plaćate za **jedan** krevet.

Ima li to smisla? Možda sam trebao drugačije?

**Comment by janko-m** [comment]
Hmm, ja sam mislio da se bracni krevet racuna kao *dva* kreveta, ne?

**Comment by silvenon** [comment]
Nisam siguran…

**Comment by silvenon** [comment]
Možda najbolje da ipak maknem krevete? Ionako je to sve otprilike, pa da pojednostavim…

**Comment by janko-m** [comment]
Ne znam, ti se tu bolje kuzis od mene, ali mislim da bi nesto trebalo biti drukcije, ili razjasnjeno, mozda mozes pitati mamu.

**Comment by silvenon** [comment]
Sređeno.
