### ISSUE TITLE
Permanent solution for photos

### ISSUE THREAD

**Issue by janko-m** [twin/waldorfcamp-web#38]
Izgleda da je Facebook token opet istekao, jer se neke slike ne prikazuju. Trebam pronaći način da dobijem trajni token ili da fizički downloadam slike.

**Comment by silvenon** [comment]
(Možemo na hrvatskom.) Ajoj, žao mi je što je to takva gnjavaža. Možemo li napraviti Flickr upload app koji nije sranje? Koristeći tvoj API.

**Comment by janko-m** [comment]
Pa možemo. Ali to onda znači da slike neće biti na Facebooku. Ili zapravo mogu slike ostati na Facebooku, i da ja imam skriptu koja reuploada slike s Facebooka na Flickr.

**Comment by silvenon** [comment]
Yep, to zvuči dobro, ako ti nije gnjavaža.

**Comment by silvenon** [comment]
Napokon smo ovo sredili 🎉
